/**
 * A specialized subclass of Employee representing an HR staff member
 * with elevated access to manage employee records and payroll in MotorPH.
 */
public class HRManager extends Employee {

    // ---------- Attributes ----------
    private int    managerId;
    private String accessLevel;

    // ---------- Constructor ----------
    public HRManager(int managerId, String accessLevel,
                     int employeeId, String firstName, String lastName,
                     String birthday, String address, String phoneNumber,
                     String sssNumber, String philhealthNumber,
                     String tinNumber, String pagibigNumber,
                     String status, Position position, Department department,
                     String immediateSupervisor, double basicSalary,
                     double riceSubsidy, double phoneAllowance,
                     double clothingAllowance) {

        super(employeeId, firstName, lastName, birthday, address, phoneNumber,
              sssNumber, philhealthNumber, tinNumber, pagibigNumber,
              status, position, department, immediateSupervisor,
              basicSalary, riceSubsidy, phoneAllowance, clothingAllowance);

        this.managerId   = managerId;
        this.accessLevel = accessLevel;
        System.out.println("[HRManager] HR access granted to: " + getFullName()
                         + " | Level: " + accessLevel);
    }

    // ---------- Methods ----------
    public void addEmployee(Employee newEmployee) {
        System.out.println("[HRManager] addEmployee() -> " + getFullName()
                         + " added new employee: " + newEmployee.getFullName()
                         + " (ID: " + newEmployee.getEmployeeId() + ")");
    }

    public void updateEmployee(Employee targetEmployee, String field, String newValue) {
        System.out.println("[HRManager] updateEmployee() -> " + getFullName()
                         + " updated " + targetEmployee.getFullName()
                         + " | Field: " + field + " -> " + newValue);
    }

    public void processPayroll(Payroll payroll) {
        System.out.println("[HRManager] processPayroll() -> " + getFullName()
                         + " is processing payroll for: "
                         + payroll.getHoursWorked() + " hrs.");
        payroll.generatePayslip();
    }

    public void approveLeaveRequest(LeaveRequest leave) {
        System.out.println("[HRManager] approveLeaveRequest() -> " + getFullName()
                         + " reviewing leave for: " + leave.getEmployee().getFullName());
        leave.approveLeave();
    }

    public void generateReport(String reportType, String period) {
        System.out.println("[HRManager] generateReport()");
        System.out.println("============================================");
        System.out.println("  MOTORPH " + reportType.toUpperCase() + " REPORT");
        System.out.println("  Period    : " + period);
        System.out.println("  Generated by: " + getFullName() + " (HR Manager)");
        System.out.println("  Access Level: " + accessLevel);
        System.out.println("============================================");
    }

    // ---------- Getters ----------
    public int    getManagerId()   { return managerId; }
    public String getAccessLevel() { return accessLevel; }
}
